.PHONY: clean All

All:
	@echo "----------Building project:[ cpp_drill - Debug ]----------"
	@"$(MAKE)" -f  "cpp_drill.mk"
clean:
	@echo "----------Cleaning project:[ cpp_drill - Debug ]----------"
	@"$(MAKE)" -f  "cpp_drill.mk" clean
